export const DELETE_USER = "DELETE_USER";
export const CREATE_USER_ITEM = "CREATE_USER_ITEM";
export const EDIT_USER = "EDIT_USER";
export const SELECTED_USER = "SELECTED_USER";
export const SELECTED_USER_PROPERTY_CHANGE = "SELECTED_USER_PROPERTY_CHANGE";
export const NEW_USER_MODAL = "NEW_USER_MODAL";
export const GET_DATA = "GET_DATA"